---
- hosts: webservers
  tasks:
    - name: Add PHP 7 PPA repository
      become: true
      apt_repository:
        repo: 'ppa:ondrej/php'
		
    - name: Install PHP CLI
      become: true
      apt:
        name: php7.1-cli
        state: latest